// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using ETModel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using UnityEngine;

namespace ETHotfix
{
    public class ConnectionManager : behaviac.Agent

    {
        private ETHotfix.ConnectionStatus ConnectionStatus = ETHotfix.ConnectionStatus.Normal;
        public void _set_ConnectionStatus(ETHotfix.ConnectionStatus value)
        {
            ConnectionStatus = value;
        }
        public ETHotfix.ConnectionStatus _get_ConnectionStatus()
        {
            return ConnectionStatus;
        }

        private int ReConnectionTimes = 0;
        public void _set_ReConnectionTimes(int value)
        {
            ReConnectionTimes = value;
        }
        public int _get_ReConnectionTimes()
        {
            return ReConnectionTimes;
        }

        public void HeartTick()
        {

            // Game.EventSystem.Run(EventIdType.TestHotfixSubscribMonoEvent, "ms");


        }

        public void Reconnection()
        {
            Log.Debug("重新连接");
            int i = RandomHelper.RandomNumber(1, 3);
            if (i == 1)
            {
                this.ConnectionStatus = ConnectionStatus.Normal;
            }
            else
            {
                this.ConnectionStatus = ConnectionStatus.Outline;
            }
        }

        public void ReturnLogin()
        {
            Log.Debug("返回登陆页面");

        }

        public void ShowStatus()
        {
            // Log.Debug(this.GetName()+"******************");
            Log.Debug("******************");
        }
    }

}



