// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

// -------------------
// Customized enums
// -------------------

namespace ETHotfix
{
	public enum ConnectionStatus
	{
		None,
		Normal,
		Unsteadiness,
		Outline,
	}
}

